#!/usr/bin/env node
/**
 * generate-config.js — Generate config.h + sdkconfig from JSON input
 *
 * Reads: config.json (from stdin or file)
 * Writes: config.h, sdkconfig.defaults (merged: root + chip + board)
 */

const fs = require('fs');
const path = require('path');

// ─── Read input ────────────────────────────────────────────────
let input;
const inputFile = process.argv[2];
if (inputFile) {
  input = JSON.parse(fs.readFileSync(inputFile, 'utf-8'));
  main(input);
} else {
  let stdin = '';
  process.stdin.setEncoding('utf-8');
  process.stdin.on('data', chunk => stdin += chunk);
  process.stdin.on('end', () => { input = JSON.parse(stdin); main(input); });
  return;
}

function main(cfg) {
  const board = cfg.board || 'bread-compact-wifi';
  const chip = cfg.chip || 'esp32s3';

  const xiaozhiRoot = path.resolve(__dirname, '..', 'xiaozhi-esp32');
  const boardDir = path.join(xiaozhiRoot, 'main', 'boards', board);
  const boardConfigH = path.join(boardDir, 'config.h');

  if (!fs.existsSync(boardConfigH)) {
    console.error(`❌ Board "${board}" not found at ${boardConfigH}`);
    process.exit(1);
  }

  // 1. Generate config.h
  let configH = fs.readFileSync(boardConfigH, 'utf-8');
  if (cfg.pins) {
    configH = applyPinOverrides(configH, cfg.pins);
  }
  if (cfg.onboard_led === false) {
    configH = configH.replace(/^#define BUILTIN_LED_GPIO\b/gm, '// #define BUILTIN_LED_GPIO');
  }
  if (cfg.extra_pins) {
    let extra = '\n// --- Extra pins from xiaozhi-builder ---\n';
    for (const [name, gpio] of Object.entries(cfg.extra_pins)) {
      if (gpio !== null && gpio !== undefined) {
        extra += `#define ${name.toUpperCase()}_GPIO GPIO_NUM_${gpio}\n`;
      }
    }
    configH += extra;
  }
  fs.writeFileSync(boardConfigH, configH);
  console.log(`✅ Generated ${boardConfigH}`);

  // 2. Merge sdkconfig: root + chip + board + language
  let sdkdefaults = '';

  // Root defaults ALWAYS included (partition table, LVGL, bootloader, compiler...)
  const rootDefaults = path.join(xiaozhiRoot, 'sdkconfig.defaults');
  if (fs.existsSync(rootDefaults)) {
    sdkdefaults = fs.readFileSync(rootDefaults, 'utf-8');
    console.log(`Loaded root defaults: ${rootDefaults}`);
  }

  // Chip-specific defaults appended
  const chipDefaults = path.join(xiaozhiRoot, `sdkconfig.defaults.${chip}`);
  if (fs.existsSync(chipDefaults)) {
    sdkdefaults += '\n# --- Chip-specific defaults ---\n';
    sdkdefaults += fs.readFileSync(chipDefaults, 'utf-8');
    console.log(`Merged chip defaults: ${chipDefaults}`);
  }

  // Board config
  sdkdefaults += '\n# --- Generated by xiaozhi-builder ---\n';
  sdkdefaults += `# Board: ${board}\n`;
  sdkdefaults += `CONFIG_BOARD_TYPE_${board.toUpperCase().replace(/-/g, '_')}=y\n`;

  // Language
  if (cfg.language) {
    const langMap = {
      zh_CN: 'LANGUAGE_ZH_CN', zh_TW: 'LANGUAGE_ZH_TW', en_US: 'LANGUAGE_EN_US',
      ja_JP: 'LANGUAGE_JA_JP', ko_KR: 'LANGUAGE_KO_KR', vi_VN: 'LANGUAGE_VI_VN',
      th_TH: 'LANGUAGE_TH_TH', de_DE: 'LANGUAGE_DE_DE', fr_FR: 'LANGUAGE_FR_FR',
      es_ES: 'LANGUAGE_ES_ES', it_IT: 'LANGUAGE_IT_IT', ru_RU: 'LANGUAGE_RU_RU',
    };
    const langConfig = langMap[cfg.language] || 'LANGUAGE_VI_VN';
    sdkdefaults += `CONFIG_${langConfig}=y\n`;
  }

  const outSdkConfig = path.join(xiaozhiRoot, 'sdkconfig.defaults');
  fs.writeFileSync(outSdkConfig, sdkdefaults);
  console.log(`✅ Generated ${outSdkConfig}`);

  // 3. Metadata
  const meta = { board, chip, language: cfg.language, generatedAt: new Date().toISOString(), pins: cfg.pins || {} };
  fs.writeFileSync(path.join(xiaozhiRoot, '.xiaozhi-builder.json'), JSON.stringify(meta, null, 2));
  console.log('✅ Build config ready');
}

function applyPinOverrides(source, pins) {
  const pinMap = {
    mic_ws: 'AUDIO_I2S_MIC_GPIO_WS',
    mic_sck: 'AUDIO_I2S_MIC_GPIO_SCK',
    mic_din: 'AUDIO_I2S_MIC_GPIO_DIN',
    spk_dout: 'AUDIO_I2S_SPK_GPIO_DOUT',
    spk_bclk: 'AUDIO_I2S_SPK_GPIO_BCLK',
    spk_lrck: 'AUDIO_I2S_SPK_GPIO_LRCK',
    i2s_ws: 'AUDIO_I2S_GPIO_WS', i2s_bclk: 'AUDIO_I2S_GPIO_BCLK',
    i2s_din: 'AUDIO_I2S_GPIO_DIN', i2s_dout: 'AUDIO_I2S_GPIO_DOUT',
    led: 'BUILTIN_LED_GPIO', boot_btn: 'BOOT_BUTTON_GPIO',
    touch_btn: 'TOUCH_BUTTON_GPIO', vol_up_btn: 'VOLUME_UP_BUTTON_GPIO',
    vol_down_btn: 'VOLUME_DOWN_BUTTON_GPIO', lamp: 'LAMP_GPIO',
    display_sda: 'DISPLAY_SDA_PIN', display_scl: 'DISPLAY_SCL_PIN',
  };
  let result = source;
  for (const [key, macro] of Object.entries(pinMap)) {
    if (pins[key] !== undefined && pins[key] !== null) {
      const regex = new RegExp(`(#define ${macro}\\s+)\\w+`, 'g');
      result = result.replace(regex, `$1GPIO_NUM_${pins[key]}`);
    }
  }
  if (pins.display_width !== undefined) {
    result = result.replace(/#define DISPLAY_WIDTH\s+\d+/, `#define DISPLAY_WIDTH ${pins.display_width}`);
  }
  if (pins.display_height !== undefined) {
    result = result.replace(/#define DISPLAY_HEIGHT\s+\d+/, `#define DISPLAY_HEIGHT ${pins.display_height}`);
  }
  return result;
}
